version: '3'
services:
  wallet:
    build:
      build:
        context: .
        args:
          REPOSITORY: 'https://github.com/shekeltechnologies/JewNew'
          REF: master
    restart: always
    ports:
      - '49472:49472'
      - '49473:49473'
    command:
      - '-rpcuser=shekel-wallet'
      - '-rpcpassword=qdwvdvvm'
      - '-server=1'
      - '-listen=0'
    volumes:
      - './wallet/:/home/shekel/'
  masternode:
    build:
      build:
        context: .
        args:
          REPOSITORY: 'https://github.com/shekeltechnologies/JewNew'
          REF: master
    restart: always
    ports:
      - '49472:49472'
      - '49473:49473'
    command:
      - '-rpcuser=shekel-mn01'
      - '-rpcpassword=qdwvdvvm'
      - '-rpcallowip=::/0'
      - '-server=0'
      - '-listen=1'
      - '-masternode=1'
      - '-masternodeprivkey=YourMasternodePrivKey'
    volumes:
      - './masternode/:/home/shekel/'
